NUM_CLIENTS = 4
NUM_ROUNDS = 10
EPOCHS_PER_CLIENT = 3
BATCH_SIZE = 1
LEARNING_RATE = 1e-4


#NEEDS TO BE CHANGED
BASE_DIR = "./"
DATA_DIR = f"{BASE_DIR}/data"
GLOBAL_MODEL_DIR = f"{BASE_DIR}/global_models"
CHECKPOINT_DIR = f"{BASE_DIR}/checkpoints"
LOGS_DIR = f"{BASE_DIR}/logs"
